server:
  port: 8081

spring:
  rabbitmq:
    request:
      host: 0.0.0.0
      port: 5672
      username: rabbitmq
      password: rabbitmq
      exchenge:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
      deadletter:
        producer: dl.producer.aula-spring

