spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/hash
    password: root
    username: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: true

grpc:
  host: localhost
  port: 50051