spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/moon
    password: root
    username: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: true

kafka:
  topics:
    create-payment: "moon-create-payment"