version: '3.8'

services:
  productapi:
    container_name: "product-api"
    build:
      context: product-api/
    ports:
    - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
      - discount
    environment:
      ENV: dev
      MYSQL_HOST: mysql-database
      MYSQL_PORT: 3306

  discount:
    container_name: "discount-service"
    build:
      context: discount-service/
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql

  mysql:
      image: mysql:8.0
      cap_add:
        - CAP_SYS_NICE
      container_name: mysql-database
      command: '--default-authentication-plugin=mysql_native_password'
      environment:
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'hash'
      ports:
        - 3306:3306
      volumes:
        - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10